server {
    listen 443 ssl;
    server_name wiki.tdw.local;
    ssl_certificate     /etc/letsencrypt/live/wiki.tdw.local/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/wiki.tdw.local/privkey.pem;
    location / {
        proxy_pass http://wiki:3000;
        proxy_set_header Host $host;
    }
}
